server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  port: 8080
  servlet:
    context-path: /strongprettyhomes/api
spring:
  datasource:
<<<<<<< HEAD
    password: 1869
=======
    password: 1234
>>>>>>> main
    url: jdbc:postgresql://localhost:5432/strongprettyhomes
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

backendapi:
  app:
    jwtSecret: homesServicesSecretKey
    jwtExpirationMs: 86400000